[project]
name = "redisconfig"
version = "0.2.0"
description = "Simple, robust Redis configuration"
authors = [
    {name = "Jeremy Carbaugh", email = "jeremy.carbaugh@xplortechnologies.com"},
    {name = "Jason Williams", email = "jason.williams@xplortechnologies.com"},
]
license = "MIT"
keywords = ["redis"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "redis>=3.0.0",
]


[project.urls]
Homepage = "https://github.com/xplor/redisconfig"
Repository = "https://github.com/xplor/redisconfig"


[dependency-groups]
dev = [
    "mypy>=1.18.2,<2",
    "pytest>=8.4.2,<9",
    "ruff>=0.14.2,<1",
    "tox>=4.32.0,<5",
    "tox-uv>=1.29.0,<2",
]


[build-system]
build-backend = "uv_build"
requires = ["uv_build"]


[tool.uv]
package = true


[tool.uv.build-backend]
module-name = "redisconfig"
module-root = ""
namespace = true
source-include = ["LICENSE"]


[tool.pytest.ini_options]
addopts = "-v -ra"
testpaths = "tests"


[tool.mypy]
files = "redisconfig"
ignore_missing_imports = true


[tool.tox]
legacy_tox_ini = """
[env]
FORMAT_PATHS = redisconfig tests

[tox]
envlist =
    py{314,313,312,311,310}-redis{3,4,5,6,7}
    mypy
    formatting
    lint
skip_missing_interpreters = true
isolated_build = true

[testenv]
extras =
    test
deps =
    redis3: redis>=3,<4
    redis4: redis>=4,<5
    redis5: redis>=5,<6
    redis6: redis>=6,<7
    redis7: redis>=7,<8
commands =
    pytest

[testenv:mypy]
commands =
    mypy --install-types --non-interactive

[testenv:formatting]
commands =
    ruff format --check

[testenv:lint]
commands =
    ruff check
"""

