name: build
on:
  push:
  pull_request:
  # Since this will likely be a low activity project we'll schedule a build
  # weekly at 4:00 AM UTC so we can stay on top of project health.
  schedule:
    - cron: "0 4 * * 1"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.14", "3.13", "3.12", "3.11", "3.10"]
    name: "Tests: Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: uv sync --dev
      - name: Tests
        run: uv run tox -e py-redis3,py-redis4,py-redis5,py-redis6,py-redis7
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
      - name: Install Requirements
        run: uv sync --dev
      - name: Formatting (black)
        run: uv run tox -e formatting
      - name: Typing (mypy)
        run: uv run tox -e mypy
      - name: Linting (flake8)
        run: uv run tox -e lint
